server:
  port: 4100

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/OAuth
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/OAuth
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: api-gateway
            client-secret: ${SPRING_SECURITY_OAUTH2_REGISTRATION_KEYCLOAK_CLIENT_SECRET}
            scope: openid

service:
  auth:
    url: http://localhost:4001
  user:
    url: http://localhost:4000
  order:
    url: http://localhost:4002
  payment:
    url: http://localhost:4003